module.exports = {
    plugins: [require("daisyui")],
    content: [
        "resources/views/*.php",
        "resources/views/**/*.php",
        "resources/views/**/**/*.php",
        "resources/views/**/**/**/*.php",
        "resources/views/**/**/**/**/*.php",
        "resources/views/**/**/**/**/**/*.php",
        "resources/views/**/**/**/**/**/**/*.php",
        "resources/js/*.js",
        "resources/ts/*.ts",
        "resources/vue/*.vue",
        "resources/vue/*.js",
        "resources/vue/*.ts",
        "resources/vue/**/*.vue",
        "resources/vue/**/*.js",
        "resources/vue/**/*.ts",
    ],
    darkMode: "class",
};
