export const landingPage = '/'
export const dashboard = '/dashboard'
export const profile = '/profile'
export const serverHorizon = '/horizon'
export const serverLogs = '/server-logs'
export const userMan = '/user-man'